---

- name: Assertions
  ansible.builtin.assert:
    that:
      - unifi_docker_data is defined

- name: Setup docker container w/ unifi
  ansible.builtin.include_tasks: install.yml

- name: Configure host
  ansible.builtin.include_tasks: config.yml
